### PR TITLE
fix avatar initials for usernames with whitespace

### LINKED ISSUE #970: Avatar nicht verfügbar wenn Name mit Leerzeichen beginnt/endet

### PR DESCRIPTION
**Pull request by bseber**
closes #970

### CODE REVIEW

File: src/main/java/de/focusshift/zeiterfassung/avatar/AvatarController.java [hunk 1]
```diff
@@ -35,11 +33,14 @@ public ResponseEntity<String> avatar(@RequestParam("name") String name, Locale l
     }
 
     private static String getInitials(String niceName) {
-        final int idxLastWhitespace = niceName.lastIndexOf(' ');
+
+        final String normalized = niceName.strip();
+
+        final int idxLastWhitespace = normalized.strip().lastIndexOf(' ');
```
Comment (derTobsch) [inline src/main/java/de/focusshift/zeiterfassung/avatar/AvatarController.java:39]: Why do we strip the normalized string again?
